//app Constants
export const LOADING = 'LOADING';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const SET_REQUEST_STATUS = 'SET_REQUEST_STATUS';

//Auth Constants
export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNUP = 'SIGNUP';
export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const AUTHENTICATING = 'AUTHENTICATING';
export const ON_AUTH_STATUS_CHANGED = 'ON_AUTH_STATUS_CHANGED';
export const ON_AUTH_STATUS_SUCCESS = 'ON_AUTH_STATUS_SUCCESS';
export const ON_AUTH_STATUS_FAIL = 'ON_AUTH_STATUS_FAILED';
export const SET_AUTH_PERSISTENCE = 'SET_AUTH_PERSISTENCE';
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

//Profile Constants
export const SET_PROFILE = 'SET_PROFILE';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

//Products Constants
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTTS_SUCCESS';

//Cart Actions
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const ADD_QTY = 'ADD_QTY';
export const MINUS_QTY = 'MINUS_QTY';

//Shipping Actions
export const SET_SHIPPING_DETAILS = 'SET_SHIPPING_DETAILS';
export const SET_SHIPPING_SUCCESS = 'SET_SHIPPING_SUCCESS';
export const RESET_SHIPPING_DETAILS = 'RESET_SHIPPING_DETAILS';
